### ISSUE TITLE
Setup Webhook with GitHub and WAC

### ISSUE THREAD

**Issue by danielcapacio** [wackydnbc/wackywebapp#21]
Setup a webhook in your team repo settings on github, linking to the WAC deployment handler. Each time you push/merge to the configured branch in your team repo, the repo will be automatically pulled and deployed on my server. It will then be accessible for testing through the subdomain with your team name, for instance https://chicken.jlparry.com.

Test the webhook, and the airline subdomain.

**Comment by nikojohnarellano** [comment]
Webhook setup to : xwing.jlparry.com
